//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AbzanovGlazki
{
    using System;
    using System.Collections.Generic;
    using System.Linq;

    public partial class AgentDB
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AgentDB()
        {
            this.AgentPriorityHistory = new HashSet<AgentPriorityHistory>();
            this.ProductSale = new HashSet<ProductSale>();
            this.Shop = new HashSet<Shop>();
        }
    
        public int ID { get; set; }
        public string Title { get; set; }
        public int AgentTypeID { get; set; }
        public string Address { get; set; }
        public string INN { get; set; }
        public string KPP { get; set; }
        public string DirectorName { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public string Logo { get; set; }
        public int Priority { get; set; }

        public string LogoOut
        {
            get
            {
                if (Logo == "")
                {
                    return "res/picture.png";
                }
                return Logo;
            }
        }
        public string AgentTypeFull
        {
            get
            {
                return AgentType.Title;
            }
        }

        public int CountProduct
        {
            get
            {
                var StartYear = new DateTime(DateTime.Now.Year, 1, 1);
                return ProductSale.Where(ps => ps.SaleDate >= StartYear).Sum(ps => ps.ProductCount);
            }
            
        }

        public int Discount
        {
            get
            {
                if (CountProduct >= 0 && CountProduct < 50000)
                    return 5;
                else return 0;
            }
        }

        public string PhoneSearch
        {
            get
            {
                return Phone.Replace("+", "").Replace("-", "").Replace("(", "").Replace(")", "");
            }
        }

        public virtual AgentType AgentType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AgentPriorityHistory> AgentPriorityHistory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductSale> ProductSale { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Shop> Shop { get; set; }
    }
}
